version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: flight_app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    working_dir: /var/www/project
    volumes:
      - ../project:/var/www/project
    networks:
      - flight-network

  webserver:
    image: nginx:alpine
    container_name: flight_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../project:/var/www/project
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flight-network

  db:
    image: postgres:15-alpine
    container_name: flight_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flight_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flight-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: flight_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: david
    ports:
      - "5050:80"
    networks:
      - flight-network

volumes:
  pgdata:

networks:
  flight-network:
    driver: bridge